### ISSUE TITLE
Song Cover

### ISSUE THREAD

**Issue by SKHasmukh** [patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP#3]
After downloading the song it doesn't show its cover... please fix this..
Or provide some solution

**Comment by patelharsh80874** [comment]
This webapp is built with react js. React js is only for frontend or client side rendering. Due to this reason I can't add cover photo in songs download functionality. Server side rendering or processing is needed to implement functionality to download songs with cover photo which cannot be implemented in webapp built with react js. Sorry but there is no solution for this.

**Comment by patelharsh80874** [comment]
**new option added for 
song download with poster/cover image embedded with all metadata**


Link : https://the-ultimate-songs-webapp-harsh-patel.vercel.app


https://github.com/patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP
